version: '2.1'

services: 
  docker-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass123
      - MYSQL_DATABASE={{cookiecutter.database_name}}
      - MYSQL_USER=foobar
      - MYSQL_PASSWORD=foobar
      - MYSQL_HOST=localhost
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpass123 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - backend

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://docker-mysql:3306/{{cookiecutter.database_name}} -schemas={{cookiecutter.database_name}} -user=foobar -password=foobar migrate
    volumes:
     - "./local-setup/sql:/flyway/sql"
    depends_on:
      docker-mysql:
        condition: service_healthy
    networks:
      - backend

  {{cookiecutter.project_name}}:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_URL=jdbc:mysql://docker-mysql:3306/{{cookiecutter.database_name}}?useSSL=false
      - MYSQL_USER=foobar
      - MYSQL_PASSWORD=foobar
    depends_on:
      - docker-mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
