version: '2.1'

services: 
{% if cookiecutter.connection_type == 'local' %}
  docker-mongo:
    image: mongo:latest
    container_name: docker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME: foobar
      - MONGO_INITDB_ROOT_PASSWORD: foobar
    networks:
      - backend
{% endif %}
  {{cookiecutter.project_name}}:
    build: .
    ports:
      - "8000:8000"
{% if cookiecutter.connection_type == 'local' %}
    depends_on:
      - docker-mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
{% endif %}

volumes:
  mongo-data: